### ___________________________________________________________________________________
@HOST=http://localhost:3001
### ___________________________________________________________________________________

GET {{HOST}}/ HTTP/1.1



### MEGA-SENA
GET https://apiloterias.com.br/app/resultado?loteria=megasena&token=AXfzBXx9JaidF7J HTTP/1.1
Content-Type: application/json

### 1-2530
GET https://apiloterias.com.br/app/resultado?loteria=megasena&token=AXfzBXx9JaidF7J&concurso=2524
Content-Type: application/json